// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"Messenger/internal/handler/http"
	"Messenger/internal/repository"
	"Messenger/internal/service"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeAuthHandler(db *sqlx.DB, authCfg service.AuthCfg) (*http.Handler, error) {
	userRepository := repository.NewUserRepository(db)
	blockedRefreshTokenRepository := repository.NewBlockedRefreshTokenRepository(db)
	auth := service.NewAuth(userRepository, blockedRefreshTokenRepository, authCfg)
	handler := http.NewHandler(auth)
	return handler, nil
}
